# -*- coding: utf-8 -*-
"""BCG X.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ul963F8m8juPRtVFSa0Qairzk75_E6M8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# from google.colab import data_table
# data_table.enable_dataframe_formatter()

# from google.colab import data_table
# data_table.disable_dataframe_formatter()

""" Create DataFrames for each company"""

msft_data = pd.DataFrame({
    'Fiscal Year': [2022, 2021, 2020],
    'Revenue (USD)': [242059, 184905, 143018],
    'Net Income (USD)': [69358, 61348, 44281],
    'Total Assets (USD)': [364113, 330640, 286556],
    'Total Debt (USD)': [73151, 67642, 63908]
})


tsla_data = pd.DataFrame({
    'Fiscal Year': [2022, 2021, 2020],
    'Revenue (USD)': [81462, 53823, 24578],
    'Net Income (USD)': [12556, 5519, -721],
    'Total Assets (USD)': [142956, 86382, 50179],
    'Total Debt (USD)': [12113, 10094, 13157]
})

aapl_data = pd.DataFrame({
    'Fiscal Year': [2022, 2021, 2020],
    'Revenue (USD)': [394328, 365348, 274515],
    'Net Income (USD)': [99803, 94692, 57411],
    'Total Assets (USD)': [352755, 323888, 260178],
    'Total Debt (USD)': [108237, 90173, 81844]
})


msft_data['Fiscal Year']

"""2.Plot revenue growth for each company


"""

plt.figure(figsize=(10,6))
plt.plot(msft_data['Fiscal Year'], msft_data['Revenue (USD)'],label='MicroSoft' )
plt.plot(tsla_data['Fiscal Year'],tsla_data['Revenue (USD)'], label='Tesla')
plt.plot(aapl_data['Fiscal Year'],aapl_data['Revenue (USD)'], label='Apple')
plt.xlabel('Fiscal Year')
plt.ylabel('Revenue (USD)')
plt.title('Revenue Growth')
plt.legend()
plt.show()



"""3. Calculate compound annual growth rate (CAGR) for revenue

"""

def calculate_cagr(data):
    revenue_2022 = data['Revenue (USD)'].iloc[0]
    revenue_2020 = data['Revenue (USD)'].iloc[2]
    cagr = (revenue_2022 / revenue_2020) ** (1/2) - 1
    return cagr

msft_cagr = calculate_cagr(msft_data)
tsla_cagr = calculate_cagr(tsla_data)
aapl_cagr = calculate_cagr(aapl_data)

print(f'Microsoft CAGR: {msft_cagr:.2%}')
print(f'Tesla CAGR: {tsla_cagr:.2%}')
print(f'Apple CAGR: {aapl_cagr:.2%}')

"""4.Calculate year-over-year changes for each financial metric


"""

def calculate_yoy_changes(data):
    data['Revenue YoY Change'] = data['Revenue (USD)'].pct_change() * 100
    data['Net Income YoY Change']=data['Net Income (USD)'].pct_change()*100
    data['Total Assets YoY Change']=data['Total Assets (USD)'].pct_change()*100
    data['Total Debt YoY Change']=data['Total Debt (USD)'].pct_change()*100
    return data

msft_data_yoy=calculate_yoy_changes(msft_data)
tsla_data_yoy=calculate_yoy_changes(tsla_data)
aapl_data_yoy=calculate_yoy_changes(aapl_data)


print(msft_data_yoy)
print(tsla_data_yoy)
print(aapl_data_yoy)